;  compile : nasm -f elf32 solution.asm; gcc -no-pie -m32 -o out solution.o; ./out
; ---------------------------------------------------------------------------------------------
;
;  Project Euler - Problem 2
;  Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
;  By starting with 1 and 2, the first 10 terms will be:
;    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;  By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
;  find the sum of the even-valued terms.  
;
; ---------------------------------------------------------------------------------------------
                global          main
                extern          printf

                section         .data
                msg             db "%i", 0x0a, 0x00		


                section         .text
main:           push            ebp
                mov             ebp, esp

                ; init values		
                mov             esi, 1          ; value 1 = 1
		mov             ebx, 2          ; value 2 = 2
                mov             edi, ebx        ; sum = 2

                ; calculate sum
loop:           mov             edx, esi
                add             edx, ebx
                cmp             edx, 4000000
                jg              done
                mov             esi, ebx
                mov             ebx, edx
                test            edx, 1          ; is odd 
                jne             odd
                add             edi, edx
odd:            jmp             loop           

                ; printing
done:           push            edi
                push            msg
                call            printf

                ; handle stack stuff
                mov             eax, 0          ; return code
                mov             esp, ebp
                pop             ebp
                ret
